baseURL = "https://blog.ashishsantikari.info"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ideas"
theme = "PaperMod"

[pagination]
pagerSize = 3

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
title = "Ideas"
description = "Micro blogging site by Ashish Santikari"
keywords = ["Blog", "JavaScript", "React"]
author = "Ashish Santikari"
# author: ["Me", "You"] # multiple authors
# images: ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.utterances]
repo = "ashishsantikari/ideas"
issueTerm = "pathname"

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
# favicon = "favicon.ico"
# favicon16x16 = "favicon-16x16.png"
# favicon32x32 = "favicon-32x32.png"
# apple_touch_icon = "apple-icon.png"
# safari_pinned_tab = "apple-icon.png"

[params.label]
text = "Ideas"
# icon = "/apple-icon.png"
# iconHeight = 35

[params.profileMode]
enabled = false # needs to be explicitly set
title = "Ideas"
subtitle = "worth sharing"
imageUrl = ""
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[params.homeInfoParams]
title = "Ideas"
content = "worth sharing"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/_jsdev"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/3985206/ashish-santikari"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ashishsantikari"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/asantikari"

# analytics:
#   google:
    # SiteVerificationTag = "XYZabc"
#   bing:
#     SiteVerificationTag = "XYZabc"
#   yandex:
#     SiteVerificationTag = "XYZabc"

# TagManager:
#   id = "your id"

[params.cover]
hidden = false # hide everywhere but not in structured data (fixed typo)
hiddenInList = true # hide on list pages and home
hiddenInSingle = false # hide on single page

[params.editPost]
disabled = true
URL = "https://github.com/ashishsantikari/ideas/content"
Text = "Suggest Changes" # edit text
appendFilePath = true # to append file path to Edit link

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[menu]

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "https://ashishsantikari.info"
weight = 40
external = true

[[menu.main]]
identifier = "privacy"
name = "Privacy"
url = "/privacy/"
weight = 50

pygmentsUseClasses = true

[markup.highlight]
noClasses = false
